### ISSUE TITLE
Issue usada para informar o repositório usado no PI

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#1]
Basta adicionar um comentário  com as seguintes informações:

- Nome do projeto
- URL do repositório no GitHub
- Nome completo dos integrantes do grupo

**Comment by marcelasilverio** [comment]
- Nome do projeto: SIGPPI - Sistema de Gestão e Pesquisa de Propriedades Intelectuais
- URL da organização no GitHub: https://github.com/cie-cefet-mg
- Repositório Público: https://github.com/cie-cefet-mg/TCC-SIGPPI
- Nomes: Marcela Prata Silvério, Izabela Amélia Marques de Andrade, Tássyla Lissa Lima, Mayara do Carmo Mendes, Isaac Portela da Silva, Mateus Leal Sobreira

**Comment by gs-coelho** [comment]
- Nome do Projeto: SpaceBooks
- URL da Organização no Github: https://github.com/TCC-SpaceBooks
- URL do repositório público no GitHub: https://github.com/TCC-SpaceBooks/SpaceBooks-Publico
- Nomes dos integrantes no grupo:
  - Bruna Carvalho Peixoto Sanches
  - Gabriel Coelho dos Santos
  - Giovana Caroba Bragio dos Santos
  - Janine de Amorim Teodoro
  - Maria Eduarda Carmona Banhos
  - Victor Wilson Medeiros da Silva

**Comment by thevinilima** [comment]
- Nome do projeto: AchaPet
- URL do repositório no GitHub: https://github.com/Danis-Corp/Doc-AchaPet
- Nome completo dos integrantes do grupo:
  - Arthur Coelho
  - Davi Rodrigues
  - Henrique Matos
  - Pedro Simões
  - Rubem Muzzi
  - Vinícius Lima

**Comment by gabriel-py** [comment]
- Nome do projeto: Debeauty
- URL do repositório no GitHub: https://github.com/gabriel-py/debeauty
- Nome completo dos integrantes do grupo: Gabriel Gonçalves de Souza Ribeiro, João Francisco Queiroga e Raquel Alexsandra do Couto

**Comment by Kochillo** [comment]
- Nome do projeto: Day By Day!
- URL do repositório no GitHub: https://github.com/JVitoor/DayByDay
- Nome completo dos integrantes do grupo: David Nunes Ribeiro, João Marcos de Sousa Rezende, João Vitor Lima Gomes, Pedro Henrique Alves de Abreu Campos e Pedro Henrique Yagi de Almeida
