### ISSUE TITLE
Issue para informar a organização e wiki do PI (LPSI 2022)

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#10]
Basta informar o link da organização, wiki, e a lista dos integrantes do grupo. Prazo: 15/04/2022.

Exemplo:

* Organização: https://github.com/cefetmg-2022-psi-gX
* Wiki: https://github.com/cefetmg-2022-psi-gX/wiki
* Integrantes:
Aluno A
Aluno B
Aluno C
Aluno D
Aluno E

__Observação:__ Uma submissão por grupo.

**Comment by tainadrumond** [comment]
- Organização: https://github.com/cefetmg-2022-psi-g1
- Wiki: https://github.com/cefetmg-2022-psi-g1/wiki

- Integrantes:

Arthur Gustavo
Gustavo Alvarenga
João Quaresma
Luisa Clara
Pedro Henrique Alve
Tainá Drumond

**Comment by malicearia** [comment]
Organização: https://github.com/cefetmg-2022-psi-g6

Wiki: https://github.com/cefetmg-2022-psi-g6/wiki

Integrantes:

Gabrielle
Letícia
Maria Alice Miranda
Thiago Iulli
Richard
Victor Schneider

**Comment by EnzoBraz** [comment]
Organização: https://github.com/cefetmg-2022-psi-g4

Wiki: https://github.com/cefetmg-2022-psi-g4/wiki

Integrantes:

Enzo de Souza Braz
Gabriel Licas
Gabriel Guimarães
Helio Antunes
Matheus Gaston
João Vitor

**Comment by GChavesR** [comment]
- Organização: https://github.com/cefetmg-2022-psi-g3

- Wiki: https://github.com/cefetmg-2022-psi-g3/wiki

Integrantes: 

Guilherme Chaves Resende
Lucas Gabriel Pimenta Moreira
Pedro Henrique Yagi de Almeida
Yuri Estevão Sales de Oliveira

**Comment by evelynlaura** [comment]
- Organização: [https://github.com/cefetmg-2022-psi-g005](url)
- Wiki: [https://github.com/cefetmg-2022-psi-g005/wiki](url)

Integrantes:

Agatha Thalita Torres Soares
Bryan Andrey Ferreira de Souza
Evelyn Laura Alves de Souza Costa
Layla Dias Siqueira Ferreira

**Comment by luizfernando103** [comment]
- Organização: https://github.com/cefetmg-2022-psi-g2
-  Wiki: https://github.com/cefetmg-2022-psi-g2/wiki
- Integrantes: 

Leônidas José
Luis Felipe Brescia
Luiz Fernando Almeida
Marcos Paulo
Vitor Gabriel
