### ISSUE TITLE
Issue para informar a página wiki do diagrama de sequência do PI (PSI 2022)

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#19]
Responder a issue informando:

* Nome do projeto
* Link para a página wiki do diagrama de sequência
* Uma resposta por grupo

**Prazo: 23/08/22, terça-feira**

**Comment by ArthurG12** [comment]
Conversor de Braille

https://github.com/cefetmg-2022-psi-g1/wiki/wiki/Diagramas-de-Sequ%C3%AAncia-do-Sistema

**Comment by evelynlaura** [comment]
Plataforma Matchmaking

[https://github.com/cefetmg-2022-psi-g005/wiki/wiki/Diagrama-de-Sequ%C3%AAncia-do-Sistema](url)

**Comment by YuriEstevaoSales** [comment]
BandApp

https://github.com/cefetmg-2022-psi-g3/wiki/wiki/Diagramas-de-Sequ%C3%AAncia-do-Sistema

**Comment by EnzoBraz** [comment]
Trenem 

https://github.com/cefetmg-2022-psi-g4/trenem-wiki/wiki/Diagrama-de-Sequ%C3%AAncia-do-Sistema

**Comment by thiagoiulli** [comment]
SIEGE

https://github.com/cefetmg-2022-psi-g6/wiki/wiki/Diagrama-de-Sequ%C3%AAncia-do-Sistema

**Comment by marcosazevedo2112** [comment]
QUEBRA GALHO

https://github.com/cefetmg-2022-psi-g2/wiki/wiki/Diagrama-de-Sequ%C3%AAncia-do-Sistema
