### ISSUE TITLE
Issue usada para informar o seu perfil no GitHub

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#2]
Basta adicionar um comentário com as seguintes informações

- Nome completo
- URL do seu perfil no GitHub

**Comment by marcelasilverio** [comment]
- Nome: Marcela Prata Silvério
- Github: https://github.com/MarcelaSilverio

**Comment by mateus123finn** [comment]
Mateus Leal Sobreira
https://github.com/mateus123finn

**Comment by IzabelaAAndrade** [comment]
- Nome: Izabela Amélia Marques de Andrade
- Github: https://github.com/IzabelaAAndrade

**Comment by BrunaSanches** [comment]
Nome: Bruna Carvalho Peixoto Sanches
Github: https://github.com/BrunaSanches

**Comment by MariaECarmona** [comment]
Maria Eduarda Carmona Banhos
https://github.com/MariaECarmona

**Comment by Enriig** [comment]
- Nome: Henrique Matos Vieira
- Github: https://github.com/Enriig

**Comment by tassyla** [comment]
- Nome: Tássyla Lissa Lima
- GitHub: https://github.com/tatitassyla

**Comment by peo5** [comment]
Pedro Matheus Simões Ferreira
https://github.com/peo5

**Comment by isaac-portela** [comment]
- Nome: Isaac Portela da Silva
- Github: https://github.com/KroosBR

**Comment by mayaramendess** [comment]
Mayara do Carmo Mendes: https://github.com/maymdc

**Comment by thevinilima** [comment]
Nome: Vinícius Lima
GitHub: https://github.com/viniilima

**Comment by gs-coelho** [comment]
Gabriel Coelho dos Santos
https://github.com/gs-coelho

**Comment by Muzzii** [comment]
Nome: Rubem Muzzi Mortimer
Github: https://github.com/Muzzii

**Comment by JanineAT** [comment]
Nome: Janine de Amorim Teodoro
Github: https://github.com/JanineAT

**Comment by victorwo** [comment]
Nome: Victor Wilson Medeiros da Silva
Github: https://github.com/victorwo

**Comment by arthurcoelhosouza** [comment]
Nome: Arthur Coelho de Souza
Github: https://github.com/Arthur71149

**Comment by GiovanaBragio** [comment]
Nome: Giovana Caroba Bragio dos Santos 
GitHub: https://github.com/giihbragio

**Comment by Raquel-Alexsandra** [comment]
Nome: Raquel Alexsandra do Couto
GitHub: https://github.com/Raquel-Alexsandra

**Comment by Joao-Queiroga** [comment]
- Nome: João Francisco Carvalho Soares de Oliveira Queiroga
- Github: https://github.com/Joao-Queiroga

**Comment by gabriel-py** [comment]
Nome: Gabriel Gonçalves de Souza Ribeiro
GitHub: https://github.com/gabriel-py

**Comment by jmsrezende** [comment]
Nome: João Marcos de Sousa Rezende
GitHub: https://github.com/JoaoMarcosRezende

**Comment by Kochillo** [comment]
Nome: João Vitor Lima Gomes
GitHub: https://github.com/JVitoor

**Comment by PYagi** [comment]
Nome: Pedro Henrique Yagi de Almeida
GitHub: https://github.com/PYagi

**Comment by Ddavidi** [comment]
Nome: David Nunes Ribeiro
Github: https://github.com/Ddavidi
