### ISSUE TITLE
Issue usada para informar a página do diagrama de classes nos wikis

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#4]
Basta adicionar um comentário com as seguintes informações:

* Nome do projeto
* URL da página no wiki
* Nome completo dos integrantes do grupo

**Comment by IzabelaAAndrade** [comment]
- Projeto SIGPPI - Sistema de Gestão e Pesquisa de Propriedades Intelectuais
- Link para a página do diagrama de classes: https://github.com/cie-cefet-mg/TCC-SIGPPI/wiki/diagrama_classes
- Integrantes do Grupo: 
 -- Isaac Portela da Silva
 -- Izabela Amélia Marques de Andrade
 -- Marcela Prata Silvério
 -- Mateus Leal Sobreira
 -- Mayara do Carmo Mendes
 -- Tássyla Lissa Lima

**Comment by MariaECarmona** [comment]
**Projeto SpaceBooks**
- Link para a página Home: [https://github.com/TCC-SpaceBooks/SpaceBooks-Publico/wiki](https://github.com/TCC-SpaceBooks/SpaceBooks-Publico/wiki )
- Link para a página do diagrama de classes: [https://github.com/TCC-SpaceBooks/SpaceBooks-Publico/wiki/Diagrama-de-Classes](https://github.com/TCC-SpaceBooks/SpaceBooks-Publico/wiki/Diagrama-de-Classes)
- Grupo:
   -- Bruna Carvalho Peixoto Sanches
   -- Gabriel Coelho dos Santos
   -- Giovana Caroba Brágio dos Santos
   -- Janine de Amorim Teodoro
   -- Maria Eduarda Carmona Banhos
   -- Victor Wilson Medeiros da Silva

**Comment by peo5** [comment]
**AchaPet**
- [Página do diagrama](https://github.com/Danis-Corp/AchaPet/wiki/Diagrama-de-Classes)
- Integrantes:
  - Arthur Coelho de Souza
  - Davi Santos Rodrigues
  - Henrique Matos Vieira
  - Pedro Matheus Simões Ferreira
  - Rubem Muzzi Mortimer
  - Vinícius Assis Lima

**Comment by Kochillo** [comment]
**Day By Day!**

-  Link para a página do diagrama de classes: https://github.com/JVitoor/DayByDay/wiki/Diagrama-de-classes
-  Integrantes do Grupo:
-- David Nunes Ribeiro
-- João Marcos de Sousa Rezende
-- João Marcos de Sousa Rezende
-- Pedro Henrique Alves de Abreu Campos
-- Pedro Henrique Yagi de Almeida

**Comment by gabriel-py** [comment]
**Debeauty!**

- Link para a página do diagrama de classes: https://github.com/gabriel-py/debeauty/wiki/Diagrama-de-Classes

- Integrantes do Grupo:
-- Gabriel Gonçalves de Souza Ribeiro
-- João Francisco Queiroga
-- Raquel Alexsandra do Couto
