### ISSUE TITLE
Issue usada para informar o seu perfil no GitHub (LPSI 2022)

### ISSUE THREAD

**Issue by alinebrito** [alinebrito/cefet-mg-psi#5]
Basta adicionar um comentário com as seguintes informações:

- Nome completo
- URL do seu perfil no GitHub

**Comment by Baianinho** [comment]
- Bryan Andrey
- https://github.com/Baianinho

**Comment by perchuts** [comment]
- Gabriel Lucas Costa Martins
- https://github.com/perchuts

**Comment by Baumora** [comment]
- Letícia Araújo
- https://github.com/Baumora

**Comment by thiagoiulli** [comment]
- Thiago Iulli
- https://github.com/thiagoiulli

**Comment by helioantunes** [comment]
- Helio Antunes
 - https://github.com/helioantunes

**Comment by augusto-rich** [comment]
- Richard Augusto de Sousa Rocha
- https://github.com/augusto-rich

**Comment by victorschneider** [comment]
- Victor Schneider do Vale
- https://github.com/victorschneider

**Comment by srcgab** [comment]
Gabrielle de Souza Costa 
https://github.com/srtpotts

**Comment by guimaguima** [comment]
- Gabriel Guimarães dos Santos Ricardo
- https://github.com/guimaguima

**Comment by luizfernando103** [comment]
- Luiz Fernando de Almeida Dias
- https://github.com/luizfernando103

**Comment by marcosazevedo2112** [comment]
- Marcos Paulo Coelho de Azevedo
- https://github.com/marcosazevedo2112

**Comment by malicearia** [comment]
- Maria Alice Miranda de Oliveira
- https://github.com/malicearia

**Comment by joaovitorfod4** [comment]
- João Vitor Lopes Fagundes

- https://github.com/joaovitorfod4

**Comment by joaovitorf4** [comment]
- João Vitor Lopes Fagundes
- https://github.com/joaovitorfod4

**Comment by VitorExl** [comment]
- Vitor Gabriel de Freitas
- https://github.com/VitorExl

**Comment by layla-dferreira** [comment]
- Layla Dias Siqueira Ferreira
- https://github.com/layla-dferreira

**Comment by tainadrumond** [comment]
- Tainá Isabela Queiroz Drumond
- https://github.com/tainaqd

**Comment by Agatha-Thalita** [comment]
- Agatha Thalita Torres Soares

- https://github.com/Agatha-Thalita

**Comment by AlvarengaGustavo** [comment]
- Gustavo Alvarenga Ribeiro Carvalho 
- [https://github.com/GustavoArc10](https://github.com/GustavoArc10)

**Comment by ArthurG12** [comment]
- Arthur Gustavo Mendes Ferreira
- https://github.com/ArthurG12

**Comment by Quaquaresma** [comment]
- João Quaresma Crisóstomo
- https://github.com/Quaquaresma

**Comment by LuisaClara** [comment]
Luisa Clara de Paula Lara Silva
https://github.com/StaryLu

**Comment by PedroYagi** [comment]
Pedro Henrique Yagi de Almeida
https://github.com/PedroYagi

**Comment by YuriEstevaoSales** [comment]
Yuri Estevão Sales de Oliveira
https://github.com/YuriEstevaoSales

**Comment by evelynlaura** [comment]
- Evelyn Laura Alves de Souza Costa
- https://github.com/evelynlaura

**Comment by LuisBrescia** [comment]
- Luís Brescia
- https://github.com/LuisBrescia

**Comment by GastonZinhow** [comment]
- Matheus Gaston
- https://github.com/GastonZinhow
- theteusviana@gmail.com

**Comment by lucasgpm** [comment]
* Lucas Gabriel Pimenta Moreira
* https://github.com/lucasgpm

**Comment by lebraga1** [comment]
- Leônidas José Furtado Braga
- https://github.com/lebraga1

**Comment by GChavesR** [comment]
- Guilherme Chaves Resende
- https://github.com/GChavesR

**Comment by EnzoBraz** [comment]
- Enzo de Souza Braz
- https://github.com/EnzoBraz
